version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: django_prod

    ports:
      - "3021:3021"
    
    volumes:
      - ./django/src:/app
      - ./docker:/app/docker

    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

    command: python manage.py runserver 0.0.0.0:3021

    restart: always

    healthcheck:
      test: ["CMD", "sh", "/app/docker/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
